[tools]
# Core languages (mise core plugins)
node = "lts"
rust = "stable"
python = "3.12"

# CLI tools (verified in mise registry)
gh = "latest"        # GitHub CLI
ripgrep = "latest"   # Fast grep (rg command)
fd = "latest"        # Fast find
bat = "latest"       # Better cat with syntax highlighting
eza = "latest"       # Modern ls replacement

[env]
mise.env_path = "./node_modules/.bin"
