[tools]
# Core languages (mise core plugins)
node = "lts"
rust = "stable"
python = "3.12"

# CLI tools (verified in mise registry)
gh = "latest"        # GitHub CLI
ripgrep = "latest"   # Fast grep (rg command)
fd = "latest"        # Fast find
bat = "latest"       # Better cat with syntax highlighting
eza = "latest"       # Modern ls replacement
jq = "latest"        # JSON processor
bottom = "latest"    # System and process monitor (htop alternative)
npm = "latest"

[env]
PATH = "./node_modules/.bin:$PATH"
