name: CI

on:
  push:
  pull_request:

jobs:
  check-home:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Check flake
        run: nix flake check ./home

      - name: Build Home Manager config
        run: nix build ./home#homeConfigurations.ksera.activationPackage
